id: e6c94c70ac3e4f2cb14cbcdb25fcba27
initial_creation_type: ocr
source_metadata:
  volumes:
    8574f2100cc143bb8ee078f06d68870a:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
